#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Neo documentation build configuration file, created by
# sphinx-quickstart on Tue Jul 25 10:23:12 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

sys.path.insert(0, os.path.abspath('.'))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.

extensions = ['m2r',
              # 'recommonmark',
              'sphinxcontrib.programoutput',
              'sphinx.ext.autodoc',
              'sphinx.ext.autosummary',
              'sphinx.ext.napoleon',
              'sphinx.ext.doctest',
              'sphinx.ext.intersphinx',
              'sphinx.ext.todo',
              'sphinx.ext.coverage',
              'sphinx.ext.mathjax',
              'sphinx.ext.viewcode',
              'sphinx.ext.githubpages',
              'sphinx.ext.graphviz',
              ]

napoleon_use_ivar = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
# source_suffix = '.rst'
source_suffix = {'.rst':'restructuredtext',
                 '.txt':'markdown',
                 '.md': 'markdown',
                 }

# source_parsers = {
#    '.md': CommonMarkParser,
# }

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'Agent'
author = 'Christian Heider Nielsen'
copyright = '2017, {author}'.format(author=author)

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# version = 'master (' + neodroid.__version__ + ' )'
release = 'master'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set 'language' from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named 'default.css' will overwrite the builtin 'default.css'.
html_static_path = ['_static']

html_baseurl = 'agent.neodroid.ml'

# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'Agentdoc'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
  # The paper size ('letterpaper' or 'a4paper').
  #
  # 'papersize': 'letterpaper',
  # The font size ('10pt', '11pt' or '12pt').
  #
  # 'pointsize': '10pt',
  # Additional stuff for the LaTeX preamble.
  #
  # 'preamble': '',
  # Latex figure (float) alignment
  #
  # 'figure_align': 'htbp',
  }

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [(master_doc,
                    'Agent.tex',
                    'Agent Documentation',
                    'Christian Heider Nielsen',
                    'manual')
                   ]

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, 'agent', 'Agent Documentation', [author], 1)]

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [(master_doc,
                      'agent',
                      'Agent Documentation',
                      author,
                      'Agent',
                      'One line description of project.',
                      'Miscellaneous',
                      )
                     ]

# -- Options for Epub output ----------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
  'python':('https://docs.python.org/', None),
  'numpy': ('http://docs.scipy.org/doc/numpy/', None),
  }

# -- A patch that prevents Sphinx from cross-referencing ivar tags -------
# See http://stackoverflow.com/a/41184353/3343043

from docutils import nodes
from sphinx import addnodes
from sphinx.util.docfields import TypedField


def patched_make_field(self, types, domain, items, **kw):
  # `kw` catches `env=None` needed for newer sphinx while maintaining
  #  backwards compatibility when passed along further down!

  # type: (List, unicode, Tuple) -> nodes.field
  def handle_item(fieldarg, content):
    par = nodes.paragraph()
    par += addnodes.literal_strong('', fieldarg)  # Patch: this line added
    # par.extend(self.make_xrefs(self.rolename, domain, fieldarg,
    #                           addnodes.literal_strong))
    if fieldarg in types:
      par += nodes.Text(' (')
      # NOTE: using .pop() here to prevent a single type node to be
      # inserted twice into the doctree, which leads to
      # inconsistencies later when references are resolved
      fieldtype = types.pop(fieldarg)
      if len(fieldtype) == 1 and isinstance(fieldtype[0], nodes.Text):
        typename = u''.join(n.astext() for n in fieldtype)
        typename = typename.replace('int', 'python:int')
        typename = typename.replace('long', 'python:long')
        typename = typename.replace('float', 'python:float')
        typename = typename.replace('type', 'python:type')
        par.extend(
            self.make_xrefs(
                self.typerolename,
                domain,
                typename,
                addnodes.literal_emphasis,
                **kw
                )
            )
      else:
        par += fieldtype
      par += nodes.Text(')')
    par += nodes.Text(' -- ')
    par += content
    return par

  field_name = nodes.field_name('', self.label)
  if len(items) == 1 and self.can_collapse:
    field_arg, content = items[0]
    body_node = handle_item(field_arg, content)
  else:
    body_node = self.list_type()
    for field_arg, content in items:
      body_node += nodes.list_item('', handle_item(field_arg, content))
  field_body = nodes.field_body('', body_node)
  return nodes.field('', field_name, field_body)


TypedField.make_field = patched_make_field
